#!/usr/bin/env bash

# fail on error

set -o errexit
set -o pipefail
set -o nounset

# get file name

__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__logfile=$__file.log

# set up logging

exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$__logfile 2>&1

# everything below will be sent to a log file

echo $__dir
echo $__file
echo $__logfile

# this will be sent to standard output

echo "$(date) : part 1 - start" >&3

