#!/bin/sh


. $XDG_CONFIG_HOME/bin/dunst_ids

icon='notification-display-brightness-medium'
bar=$(progressbar $(getbright --raw) $(getbright --max))

dunstify -i $icon -t 2000 -r $id_brightness 'Brightness' "$bar"

