#!/bin/sh

pactl list sinks |
	awk '/Mute:/ {print " "$2}' |
	sed -n "$(getsink)p" |
	sed 's/no/墳/;s/yes/ﱝ/' |
	tr -d '\n'

pactl list sinks |
	awk '/^\s*Volume:/ {print " "$5}' |
	sed -n "$(getsink)p"
