#!/bin/sh

isup() {
	[ $(cat /sys/class/net/$1/operstate) = 'up' ]
}

ssid() {
	iwconfig 2>/dev/null | awk -F\" "/$1/ {print \$2}" | tr -d '\n'
}

card=$(cat $XDG_CONFIG_HOME/bin/wifi_interface)

isup $card &&
	echo -n "   $(ssid $card)  " ||
	echo -n ' 睊   '
