#!/bin/sh
#
# output format:  cases  todayCases ﮊ deaths  todayDeaths

# save data to cache every day

lastmodified="$(stat -c %y ~/.cache/corona 2>/dev/null | cut -d' ' -f1)"
today=$(date '+%Y-%m-%d')
url='https://corona.lmao.ninja/states'
[ "$lastmodified" != "$today" ] && curl -s "$url" >~/.cache/corona

# parse data on demand

cat ~/.cache/corona |
	jq -r '.[] | select(.state == "Arizona") | values[]' |
	tr '\n' ' ' |
	awk '{print " "$2"  "$3" ﮊ "$4"  "$5}'
