#!/bin/sh

names() {
	awk '{print $1}' "$1"
}

getlink() {
	read -r choice
	awk "/^$choice / {print \$2}" "$1"
}

copy() {
	xclip -selection 'clipboard' -in
}

file="$XDG_CONFIG_HOME"/bin/zoom

names "$file" | dmenu | getlink "$file" | copy
