#!/bin/sh

# $1 is the low battery threshold

export XDG_RUNTIME_DIR=/run/user/1000
export DBUS_SESSION_BUS_ADDRESS=unix:path="$XDG_RUNTIME_DIR"/bus

. $XDG_CONFIG_HOME/bin/dunst_ids

status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)

[ "$status" = 'Discharging' ] && [ "$capacity" -le "$1" ] &&
	dunstify -i 'notification-battery-000' -r "$id_battery" -u critical 'Battery low'
