#!/bin/sh

ping -q -c 1 1.1.1.1 >/dev/null ||
	dunstify 'Package Update' 'Error connecting to the internet'

sudo pacman -Syyu --noconfirm ||
	dunstify 'Package Update' 'Error updating with pacman'

yay -Syyu --noconfirm ||
	dunstify 'Package Update' 'Error updating with yay'
