#!/bin/sh

class="$(find ~/asu -maxdepth 1 -type d -name 'cse*' -printf '%f\n' | sort | dmenu)"
[ -z "$class" ] && exit

recordings=~/asu/"$class"/recordings

lecture="$(cut -d, -f1 <"$recordings" | dmenu)"
[ -z "$lecture" ] && exit

awk -F, -v lecture="$lecture" '$1 ~ lecture {print $2,$3}' <"$recordings" | {
	read -r password link
	echo $password | xsel -ib
	xdg-open "$link"
}
