#!/bin/sh

# retrieve config variables
. $XDG_CONFIG_HOME/bin/lock_vars

# enable dpms
xset +dpms
# set dpms timeouts
xset dpms $s_standby $s_suspend $s_off
# enable xss-lock to trigger on suspend
xss-lock slock &
