#!/bin/bash

options=("lock" "quit" "refresh" "restart" "shutdown")

option=$(printf '%s\n' "${options[@]}" | dmenu)

case "$option" in
	"lock")
		echo "lock screen"
		slock
		;;
	"quit")
		echo "quit dwm"
		dwm_kill
		;;
	"refresh")
		echo "refresh dwm"
		killall -q dwm
		;;
	"restart")
		echo "restart"
		reboot
		;;
	"shutdown")
		echo "shutdown"
		shutdown now
		;;
	*)
		echo "choose a valid option"
		;;
esac

