#!/bin/sh

case "$(printf 'lock quit refresh reboot shutdown' | tr ' ' '\n' | dmenu)" in
	lock) slock ;;
	quit) pkill -x dwmloop ;;
	refresh) pkill -x dwm ;;
	reboot) reboot ;;
	shutdown) shutdown now ;;
esac
