#!/bin/sh

lshome() {
	find $HOME -type d -path '*/\.*' -prune -o -not -name '.*' -type f -name '*.pdf' -print \
		| sed "s|$HOME|~|"
}

lstmp() {
	find /tmp/vim-latex-live-preview-* -name '*.pdf' \
		| sed -r "s|/tmp/vim-latex-live-preview-(\w*)$HOME|tmp-\1|"
}

lshome
lstmp
