#!/bin/sh

# prints all pdf files in $HOME
# i don't really know how this works
find "$HOME" -type d -path '*/\.*' -prune -o -not -name '.*' -type f -name '*.pdf' -print |
	uniq | sort | sed "s|$HOME|~|"
