#!/bin/sh
#
# copy password to clipboard

select () {
	find $PASSWORD_STORE_DIR -type f -name '*.gpg' \
		| sed "s|$PASSWORD_STORE_DIR/||" \
		| sed 's|\.gpg||' \
		| dmenu -i
}

pass show -c $(select)

