#!/bin/sh

passwords() {
	fd -e gpg . "$PASSWORD_STORE_DIR" | sed -r "s|$PASSWORD_STORE_DIR/(.*).gpg|\1|g"
}

edit() {
	read -r line
	[ -n "$line" ] && pass edit "$line"
}

delete() {
	while read -r line; do
		[ -n "$line" ] && pass rm "$line"
	done
}

case "$1" in
	'ls')
		passwords | fzf --preview='pass show {}' | edit
		;;
	'rm')
		passwords | fzf -m --preview='pass show {}' | delete
		;;
esac
