#!/bin/sh

lspdf () {
	find $HOME -type d -path '*/\.*' -prune -o -not -name '.*' -type f -name '*.pdf' -print \
}

files="$(lspdf | dmenu)"

if [ -n "$files" ]
then
	xid=$(tabbed -cd)
	echo "$xid"
	for file in $files
	do
		echo "$file"
		zathura -e "$xid" "$file" &
	done
fi

