#!/bin/sh

lshome() {
	find $HOME -type d -path '*/\.*' -prune -o -not -name '.*' -type f -name '*.pdf' -print \
		| sed "s|$HOME|~|"
}

lstmp() {
	find /tmp/vim-latex-live-preview-* -name '*.pdf' \
		| sed "s|$HOME|~|"
}

lspdf() {
	lstmp &
	lshome
}

open() {
	xid=$(tabbed -cd)
	echo "$xid"
	while read -r line; do
		echo "$line"
		zathura -e "$xid" "$line" &
	done
}

lspdf | dmenu | uniq | open
