#!/bin/sh

# if given the -n or --new-instance flag
# create a new instance
# else if there is one tabbed instance
# use that instance
# else if there are multiple tabbed instances
# select an instance

getxid() {
	icount="$(xwininfo -children -root | grep 'tabbed' | wc -l)"

	if [ "$1" = '-n' ] || [ "$1" = '--new-instance' ] || [ "$icount" -eq 0 ]; then
		tabbed -cd
	elif [ "$icount" -eq 1 ]; then
		xwininfo -children -root | awk '/tabbed/ {print $1}'
	else
		xwininfo | awk '/Window id/ {print $4}'
	fi
}

open() {
	echo "$1"
	while read -r line; do
		echo "$line"
		zathura -e "$1" "$line" &
	done
}

lspdf | dmenu | uniq | open "$(getxid "$@")"
