#!/bin/sh

. $XDG_CONFIG_HOME/bin/dunst_ids

# screenshot directory
dir="$XDG_PICTURES_DIR"/screenshots
cd $dir
# take screenshot and save it to dir
scrot $@ -e 'echo $f && sxiv $f'

# shorten dir
dir=$(echo "$dir" | sed "s|$HOME|~|")
# send notification
dunstify -i 'camera-on' -t 2000 -r "$id_shot" 'Screenshot' "Stored in $dir/"
