#!/bin/sh

. $XDG_CONFIG_HOME/bin/dunst_ids

# get directory name and shorten it
dir=$(echo "$XDG_PICTURES_DIR"/screenshots | sed "s|$HOME|~|")
# take screenshot and save it to dir
scrot -s -e 'echo $f && sxiv $f'
# send notification
dunstify -i 'camera-on' -t 2000 -r "$id_shot" 'Screenshot' "Stored in $dir/"

