#!/bin/sh

# which sink to use
getsink() {
	# basically, if my headphones are plugged in, use that sink
	# otherwise, use sink 0
	pactl list sinks short | awk 'END {print $1}'
}

# parse flags
case "$1" in
	'-s' | '--set-volume')
		pactl set-sink-volume "$(getsink)" "$2"
		;;
	'-t' | '--toggle-mute')
		pactl set-sink-mute "$(getsink)" 'toggle'
		;;
esac
