#!/bin/sh

cd ~/.scripts/
files=$(find . \( ! -regex '.*/\..*' \) -type f)

for file in $files
do
	if [ -x "$file" ]
	then
		cp $file ~/.bin/
		filename=$(basename $file)
		printf "moved \t%-40s to \t~/.bin/%s\n" "$file" "$filename"
	fi
done

