#!/bin/sh

SCRIPTS_DIR=/home/kesav/.local/scripts
BIN_DIR=/home/kesav/.local/bin

cd $SCRIPTS_DIR
files=$(find . \( ! -regex '.*/\..*' \) -type f)

echo "\nclearing $BIN_DIR:\n"

rm -rfv $BIN_DIR && mkdir $BIN_DIR

echo "\nadding scripts to $BIN_DIR/\n"

for file in $files
do
	if [ -x "$file" ]
	then
		ln -sv $(realpath $file) $BIN_DIR/$(basename $file)
	fi
done

echo "\n"

