#!/bin/sh

SCRIPTS_DIR=/home/kesav/.local/scripts
BIN_DIR=/home/kesav/.local/bin

autodelete () {

	while read newfile
	do
		filename=$(echo $newfile | awk '{print $3}')
		binpath="$BIN_DIR/$filename"

		# remove symlink
		[ -h "$binpath" ] && rm "$binpath"
	done

}

inotifywait -m -r -e delete "$BIN_DIR" | autodelete

