#!/bin/sh

SCRIPTS_DIR=/home/kesav/.local/scripts/

cd $SCRIPTS_DIR
files=$(find . \( ! -regex '.*/\..*' \) -type f)

for file in $files
do
	if [ -x "$file" ]
	then
		filename=$(basename $file)
		echo $filename
	fi
done

