#!/bin/sh

cd /home/kesav/.local/scripts/
files=$(find . \( ! -regex '.*/\..*' \) -type f)

echo "\nclearing /home/kesav/.local/bin:\n"

rm -rfv /home/kesav/.local/bin/ && mkdir /home/kesav/.local/bin/

echo "\nadding scripts to /home/kesav/.local/bin/\n"

for file in $files
do
	if [ -x "$file" ]
	then
		ln -sv $(realpath $file) /home/kesav/.local/bin/$(basename $file)
	fi
done

echo "\n"

