#!/bin/sh

autodelete () {

	while read newfile
	do
		filename=$(echo $newfile | awk '{print $3}')
		bindir="/home/kesav/.local/bin"
		binpath="$bindir/$filename"

		# remove symlink
		[ -h "$binpath" ] && rm "$binpath"
	done

}

monitordir="/home/kesav/.scripts/"
inotifywait -m -r -e delete "${monitordir}" | autodelete

