#!/bin/sh

autodelete () {

	while read newfile
	do
		filename=$(echo $newfile | awk '{print $3}')
		filepath="$BINPATH/$filename"

		# remove symlink
		[ -h "$filepath" ] && rm "$filepath"
	done

}

inotifywait -m -r -e delete "$BINPATH" | autodelete

