#!/bin/sh

SCRIPTS_DIR=/home/kesav/.local/scripts
BIN_DIR=/home/kesav/.local/bin

autolink () {

	while read newfile
	do
		dirname=$(echo $newfile | awk '{print $1}')
		filename=$(echo $newfile | awk '{print $3}')

		fullpath="$dirname$filename"
		binpath="$BIN_DIR/$filename"

		# if file is executable but not in $bin_dir
		if [ -x "$fullpath" ] && [ ! -e "$binpath" ]
		then
			# create a symlink to the file
			ln -sv "$fullpath" "$binpath"
		fi
	done

}

inotifywait -m -r -e attrib "$SCRIPTS_DIR" | autolink

