#!/bin/bash
#
# $1 is standby timeout in minutes
# $2 is suspend timeout in minutes
# $3 is off timeout in minutes
#

# calculate standby timeout in seconds
standby_timeout_sec=$(echo "$1 * 60" | bc)
# calculate standby timeout in seconds
suspend_timeout_sec=$(echo "$2 * 60" | bc)
# calculate off timeout in seconds
off_timeout_sec=$(echo "$3 * 60" | bc)

# enable dpms
xset +dpms

# set dpms timeouts
xset dpms $standby_timeout_sec $suspend_timeout_sec $off_timeout_sec

# send notification
echo "DPMS enabled"

