#!/bin/bash

#
# toggles dpms state, ie:
# if dpms is enabled, disable it
# if dpms is disabled, enable it
#
toggle_dpms () {

	dpms_status=$(xset q | grep "DPMS is " | grep -oE '[^ ]+$')

	if [ "$dpms_status" = "Disabled" ]
	then
		# enable dpms
		dpms_init $1 $2 $3 1>/dev/null 2>&1
		# send notification
		echo 'DPMS enabled'

	elif [ "$dpms_status" = "Enabled" ]
	then
		# disable dpms
		xset -dpms 1>/dev/null 2>&1
		# send notification
		echo 'DPMS disabled'

	else
		# send notification
		echo 'DPMS error'
	fi
}

toggle_dpms "$@"

