#!/usr/bin/env bash


#
# $1 is the wanted dpms status
#
# current		next		action
# disabled		disabled	do nothing
# disabled		enabled		enable dpms
# enabled		disabled	disable dpms
# enabled		enabled		do nothing
#
# ex: dpms "Enable"
# ex: dpms "Disable"
#
set_dpms () {

	dpms_status=$(xset q | grep "DPMS is " | grep -oE '[^ ]+$')

	if [ "$dpms_status" = "Disabled" ] && [ "$1" = "Enable" ]
	then
		echo "$(date +%x_%H:%M:%S:%N)	dpms status:		enable"

		xset +dpms

	elif [ "$dpms_status" = "Enabled" ] && [ "$1" = "Disable" ]
	then
		echo "$(date +%x_%H:%M:%S:%N)	dpms status:		disable"

		xset -dpms

	else
		echo "$(date +%x_%H:%M:%S:%N)	dpms status:		do nothing"
	fi
}


set_dpms "$@"

