#!/bin/bash
#
# $1 is dpms timeout in minutes
#

# calculate dpms timeout in seconds
display_timeout_sec=$(echo "$1 * 60" | bc)

# enable dpms
xset +dpms

# set dpms timeouts
xset dpms 0 $display_timeout_sec 0

# send notification
echo "DPMS enabled"

