#!/usr/bin/env bash


#
# $1 is the wanted timeout
#
# if the current timeout is different from the wanted timeout,
# set timeout to $1
# otherwise,
# do nothing
#
# ex: set_timeout 600
#
set_dpms_timeout () {

	dpms_timeout=$(xset q | grep 'Standby' | awk '{print $2}')

	if [ "$dpms_timeout" != "$1" ]
	then
		echo "$(date +%x_%H:%M:%S:%N)	dpms timeout:		set timeout to $1"

		xset dpms $1 0 0
	else
		echo "$(date +%x_%H:%M:%S:%N)	dpms timeout:		do nothing"
	fi
}


set_dpms_timeout "$@"

