#!/bin/bash

# retrieve shared variables
source $XDG_CONFIG_HOME/bin/screensaver_vars

# initialize dpms
md=$(dpms_init $standby_timeout $suspend_timeout $off_timeout)

# initialize xss
mx=$(xss_init)

# send notification
dunst_screensaver "$md" "$mx"

