#!/bin/bash

# retrieve shared variables
source ~/.local/bin/screensaver_vars

# initialize dpms
md=$(~/.local/bin/dpms_init $standby_timeout $suspend_timeout $off_timeout)

# initialize xautolock
mx=$(~/.local/bin/xautolock_init $locker_timeout)

# send notification
~/.local/bin/dunst_screensaver "$md" "$mx"

