#!/bin/bash

# retrieve shared variables
source screensaver_vars

# toggle dpms
md=$(dpms_toggle $standby_timeout $suspend_timeout $off_timeout)

# toggle xautolock
mx=$(xautolock_toggle $locker_timeout)

# send notification
dunst_screensaver "$md" "$mx"

