#!/bin/bash

# retrieve shared variables
source $XDG_CONFIG_HOME/bin/screensaver_vars

# toggle dpms
md=$(dpms_toggle $standby_timeout $suspend_timeout $off_timeout)

# toggle xss
mx=$(xss_toggle)

# send notification
dunst_screensaver "$md" "$mx"

