#!/bin/bash
#
# $1 is locker timeout
#


# kill previous instances of xautolock
killall -q xautolock

# enable xautolock (with corner support)
# xautolock -time $1 \
# 	-locker ~/.bin/i3_lockcolor \
# 	-notify 10 \
# 	-notifier "~/.bin/dunst_xautolock" \
# 	-corners 000- \
# 	-cornersize 30 &

# enable xautolock (without corner support)
xautolock -time $1 \
	-locker ~/.bin/i3_lockcolor \
	-notify 10 \
	-notifier "~/.bin/dunst_xautolock" &

# send notification
echo "Locker enabled"

