#!/bin/bash
#
# $1 is locker timeout
#

toggle_xautolock () {

	# checks if there is a process of xautolock already running
	x_running=$(ps aux | awk '$11=="xautolock"')

	# if xautolock is not running
	if [ -z "$x_running" ]
	then
		# initialize xautolock
		. /home/kesav/.bin/xautolock_init $1 &> /dev/null
		# send notification
		echo 'Locker enabled'

	# if xautolock is running
	elif [ ! -z "$x_running" ]
	then
		# kill all instances xautolock
		killall -q xautolock &> /dev/null
		# send notification
		echo 'Locker disabled'

	else
		# send notification
		echo 'Locker error'
	fi
}

toggle_xautolock "$@"

