#!/bin/bash

toggle_xsslock () {

	# checks if there is a process of xss-lock already running
	x_running=$(ps aux | awk '$11=="xss-lock"')

	# if xss-lock is not running
	if [ -z "$x_running" ]
	then
		# initialize xss-lock
		xss_init $1 1>/dev/null 2>&1
		# send notification
		echo 'Locker enabled'

	# if xss-lock is running
	elif [ ! -z "$x_running" ]
	then
		# kill all instances of xss-lock
		killall -q xss_init 1>/dev/null 2>&1
		# send notification
		echo 'Locker disabled'

	else
		# send notification
		echo 'Locker error'
	fi
}

toggle_xsslock "$@"

