#!/bin/bash


# kill previous instances of xss-lock
killall -q xss-lock

# enable xss-lock to trigger on suspend
nohup xss-lock slock >$SCRIPTSPATH/.logs/xss_lock.log 2>&1 &

# send notification
echo "Locker enabled"

