#!/bin/bash


source ~/.bin/dunst_ids

muted=$(~/.bin/audio_ismuted | grep 'not')
volume=`~/.bin/audio_getvolume`

icon_mute=~/.icons/fa-5.10.1-desktop/svgs/solid/volume-mute.svg
icon_vol=~/.icons/fa-5.10.1-desktop/svgs/solid/volume-up.svg

bar=$(~/.bin/dunst_bar $volume 100)

if [ -z "$muted" ]
then
	dunstify -i $icon_mute -t 2000 -r $id_volume 'Volume' "\nVolume muted\n$bar"
else
	dunstify -i $icon_vol -t 2000 -r $id_volume 'Volume' "\nVolume not muted\n$bar"
fi

