#!/bin/dash
#
# $1 is the directory where pictures are stored
#

. $XDG_CONFIG_HOME/bin/dunst_ids

icon='camera-on'
dir=$(echo "$1" | sed "s|$HOME|~|")

dunstify -i "$icon" -t 2000 -r "$id_shot" 'Screenshot' "Stored in $dir/"

