#!/bin/bash


source dunst_ids

icon=~/.icons/fa-5.10.1-desktop/svgs/solid/adjust.svg
bar=$(dunst_bar `bright_get` `bright_getmax`)

dunstify -i $icon -t 2000 -r $id_brightness 'Brightness' "\n$bar"

