#!/bin/bash
#
# $1 is dpms message
# $2 is xautolock message
#

source dunst_ids

icon_lock=~/.icons/fa-5.10.1-desktop/svgs/solid/lock.svg
dunstify -t 2000 -i $icon_lock -r $id_screensaver 'Screensaver' "\n$1\n$2"

