#!/bin/sh
#
# $1 is battery mode: critical, low or full
#

. $XDG_CONFIG_HOME/bin/dunst_ids

if [ "$1" = 'critical' ]
then
	icon='notification-battery-000'
	dunstify -i $icon -r $id_battery -u critical 'Battery very low' &

elif [ "$1" = 'low' ]
then
	icon='notification-battery-low'
	dunstify -i $icon -r $id_battery 'Battery low' &

elif [ "$1" = 'full' ]
then
	icon='battery-full'
	dunstify -i $icon -r $id_battery 'Battery full' &
fi

