#!/bin/bash
#
# $1 is the directory where pictures are stored
#

source dunst_ids

# convert the /home/user to ~
# it's shorter, and i am very bored
dir=$(echo "$1" | sed "s|$HOME|~|")

dunstify -t 2000 -r $id_shot 'Screenshot' "Stored in $dir"

