#!/bin/bash


source dunst_ids

muted=$(audio_ismuted | grep 'not')
volume=`audio_getvolume`

icon_mute="$ICONPATH/svgs/solid/volume-mute.svg"
icon_vol="$ICONPATH/svgs/solid/volume-up.svg"

bar=$(dunst_bar $volume 100)

if [ -z "$muted" ]
then
	dunstify -i $icon_mute -t 2000 -r $id_volume 'Volume' "\nMuted\n$bar"
else
	dunstify -i $icon_vol -t 2000 -r $id_volume 'Volume' "\nNot muted\n$bar"
fi

