#!/bin/sh

. $XDG_CONFIG_HOME/bin/dunst_ids

volumeicon () {
	case "$(volctl --is-muted)" in
		'yes')
			echo 'notification-audio-volume-muted'
			;;
		*)
			echo 'notification-audio-volume-high'
			;;
	esac
}

bar=$(dunst_bar $(volctl --get-volume) 100)

dunstify -i "$(volumeicon)" -t 2000 -r $id_volume 'Volume' "$bar"

