#!/bin/bash


source $XDG_CONFIG_HOME/bin/dunst_ids

icon='notification-display-brightness-medium'
bar=$(dunst_bar $(bright_get) $(bright_getmax))

dunstify -i $icon -t 2000 -r $id_brightness 'Brightness' "$bar"

