#!/bin/bash
#
# $1 is the directory where pictures are stored
#

source dunst_ids

icon='camera-on'
dir=$(echo "$1" | sed "s|$HOME|~|")

dunstify -i "$icon" -t 2000 -r "$id_shot" 'Screenshot' "Stored in $dir/"

