#!/bin/dash
#
# $1 is dpms message
# $2 is xautolock message
#

. $XDG_CONFIG_HOME/bin/dunst_ids

icon_lock="$ICONPATH/svgs/solid/lock.svg"
dunstify -t 2000 -i $icon_lock -r $id_screensaver 'Screensaver' "\n$1\n$2"

