#!/bin/bash
#
# $1 is the progress value
# $2 is the maximum value
#

progress=$1
max=$2
shrink=5


progress_bar="$(seq -s "─" $(($progress / $shrink + 1)) | sed 's/[0-9]//g')"
spacing_bar="$(seq -s "  " $((($max - $progress) / $shrink + 1)) | sed 's/[0-9]//g')"

bar="$progress%: |$progress_bar$spacing_bar|"

echo "$bar"

