#!/bin/sh
#
# changes brightness by given amount
#

# remove % symbol from input
# convert input to a number
arg="$(($(echo $1 | sed 's/%//g') + 0))"

# get current and full brightness
current="$(cat /sys/class/backlight/intel_backlight/brightness)"
full="$(cat /sys/class/backlight/intel_backlight/max_brightness)"

# calculate n% of maximum brightness
# add to current brightness
newbright="$(echo "$current + $arg * $full / 100" | bc)"

# remove decimal places
# write new brightness to file
echo ${newbright%.*} >/sys/class/backlight/intel_backlight/brightness
