#!/bin/sh

getraw() {
	cat '/sys/class/backlight/intel_backlight/brightness'
}

getmax() {
	cat '/sys/class/backlight/intel_backlight/max_brightness'
}

getpercent() {
	echo "100 * $(getraw) / $(getmax)" | bc
}

case "$1" in
	'-r' | '--raw')
		getraw
		;;
	'-m' | '--max')
		getmax
		;;
	'-p' | '--percent')
		getpercent
		;;
esac
