#!/bin/sh

search() {
	awk -v sink="$1" 'BEGIN {e=1} $2~sink {print $1; e=0} END {exit e}' $2
}

pactl list sinks short >$XDG_CACHE_HOME/bin/tmp
search 'bluez_sink.D0_8A_55_1F_E1_BE.a2dp_sink' $XDG_CACHE_HOME/bin/tmp ||
	search 'alsa_output.usb-0b0e_Jabra_Link_370_70BF9260C742011500-00.analog-stereo' $XDG_CACHE_HOME/bin/tmp ||
	search 'alsa_output.pci-0000_00_1f.3.analog-stereo' $XDG_CACHE_HOME/bin/tmp
