#!/bin/sh

bigmon=HDMI-1
smallmon=eDP-1

alias m='bspc monitor'
alias d='bspc desktop'

alias lsm='bspc query --monitors --names'
alias lsd='bspc query --desktops --names --monitor'

debug() {
	lsm | while read -r i; do
		echo -n "$i: "
		lsd "$i" | tr '\n' ' '
		echo
	done
}

echo --------------------
echo disconnect

echo initial state:
debug

# lsm | grep "$bigmon" >/dev/null || return
if [ "$(lsd $bigmon)" = 'tmp' ]; then
	echo $bigmon is disconnected, returning
	return
fi
echo $bigmon is connected, continuing

if lsd "$bigmon" | grep 'tmp' >/dev/null; then
	echo $bigmon has tmp, do nothing
else
	echo $bigmon does not have tmp, add temp

	m "$bigmon" --add-desktops 'tmp'

	echo added temp
fi

debug

echo moving desktops

lsd "$bigmon" | grep -v 'tmp' | while read -r i; do
	d "$i" --to-monitor "$smallmon"
done

echo moved desktops

debug

echo reordering desktops

m "$smallmon" --reorder-desktops $(lsd "$smallmon" | sort)

echo reordered desktops

debug

echo disconnecting monitor

xrandr --output "$bigmon" --auto --off

echo disconnected monitor
echo --------------------
