#!/bin/sh
#
# set brightness to given amount
#

# remove % symbol from input
# convert input to a number
arg="$(($(echo $1 | sed 's/%//g') + 0))"

# get full brightness
full="$(getbright --max)"

# calculate n% of maximum brightness
# write new brightness to file
echo $arg * $full / 100 | bc >/sys/class/backlight/intel_backlight/brightness
