#!/bin/bash


sinks=$(~/.bin/audio_listsinks)
numsinks=$( printf '%s\n' "${sinks[@]}" | wc -l )

# echo "numsinks: $numsinks"

# echo "sinks:"
# printf '%s\n' "${sinks[@]}"


if [ "$numsinks" -eq 0 ]
then
	# echo "no sinks"

	echo '0'

else
	# echo "one or more sinks"

	lastsink=$( printf '%s\n' "${sinks[@]}" | tail -n 1 )

	echo $lastsink
fi

