#!/bin/bash

# add 1 to sink
sink=$(($(audio_getusablesink)+1))
# extract volume (digits only) for that specific sink
pactl list sinks | awk "/^\sVolume: / {i++} i==$sink {print \$5;exit} " | grep -o '[0-9]*'

