#!/bin/bash

# limitations of this script:
# it can only get the active sink if audio is currently playing

sink=$( pactl list sinks short | grep 'RUNNING' | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,' )

echo $sink

