#!/bin/sh

sink=$( audio_getusablesink )

muted=$( pactl list sinks | grep 'Mute: ' | head -n $(( $sink + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

ismuted=$( echo "$muted" | grep 'yes' )

[ -n "$ismuted" ] && echo "muted" || echo "not muted"

