#!/bin/dash

# smarter check:
# get currently running sink
# running_sink=`pactl list sinks short | awk '/RUNNING/ {print $1}'`
# print either the current sink or the backup sink
# [ -n "$running_sink" ] && echo $running_sink \
# 	|| pactl list sinks short | awk 'END {print $1}'


# dumber check:
# see if this is sufficient
# basically, if my headphones are plugged in, use that sink
# otherwise, use sink 0
# i don't think i need something smarter than this
pactl list sinks short | awk 'END {print $1}'

