#!/bin/bash

# this script checks if this device is playing any audio
# TODO: update the audio/audio_isrunning script to use pactl


# this function checks the statuses of all sound cards
# returns RUNNING if any of them are running
# returns CLOSED otherwise
any_running () {

	# retreives information on the status of sound cards
	files=$(ls -1d -- /proc/asound/card*/pcm*/sub*/status)

	for file in $files
	do
		# look for the string 'RUNNING' in the file
		state=$(cat $file | grep 'RUNNING')

		# if the string is not empty, ie. contains 'RUNNING'
		if [ ! -z "$state" ]
		then
			echo "RUNNING"
			# exit immediately, no need to check the others
			return 0
		fi
	done

	# if none of the files contain 'RUNNING',
	# no audio is playing
	echo "CLOSED"
}

any_running
# while true; do any_running; sleep 1; done

