#!/bin/sh

# add 1 to sink
sink=$(audio_getusablesink)
# get line number of sink
ln=$(pactl list sinks short | awk "/^$sink/{print NR}")
# extract volume (digits only) for that specific sink
pactl list sinks | awk "/^\sVolume: / {i++} i==$ln {print \$5;exit} " | grep -o '[0-9]*'


