#!/bin/sh
#
# returns 'yes' or ''
#

# smarter check:
# add 1 to sink
# sink=$(($(audio_getusablesink)+1))
# extract if that specific sink is muted
# pactl list sinks | awk "/Mute: / {i++} i==$sink{print \$2;exit}"

# dumber check:
# check if any sinks are running
pactl list sinks | awk '/Mute: yes/ {print $2}'

