#!/bin/sh
#
# returns info on battery
# -s or --set-volume
# -t or --toggle-mute
# -g or --get-volume
# -m or --is-muted

# set volume
if [ "$1" = '-s' ] || [ "$1" = "--set-volume" ]
then
	pactl set-sink-volume "$(getsink)" "$2"
	dunst_volume

# toggle mute
elif [ "$1" = '-t' ] || [ "$1" = "--toggle-mute" ]
then
	pactl set-sink-mute "$(getsink)" 'toggle'
	dunst_volume

# get volume
elif [ "$1" = '-g' ] || [ "$1" = "--get-volume" ]
then
	# get volume from given sink
	pactl list sinks | sinkvolume.awk -v sink="$(getsink)"

# is muted
elif [ "$1" = '-m' ] || [ "$1" = "--is-muted" ]
then
	# check if the given sink is muted
	# returns yes or no
	pactl list sinks | sinkmuted.awk -v sink="$(getsink)"
fi

