#!/bin/sh
#
# returns info on battery
# -s or --set-volume
# -t or --toggle-mute

# set volume
if [ "$1" = '-s' ] || [ "$1" = "--set-volume" ]; then
	pactl set-sink-volume "$(getsink)" "$2"

# toggle mute
elif [ "$1" = '-t' ] || [ "$1" = "--toggle-mute" ]; then
	pactl set-sink-mute "$(getsink)" 'toggle'
fi
