#!/bin/sh
#
# connects given device

# prompt names of devices, retrieve selected
name=$(echo 'devices' | bluetoothctl \
	| sed -rn 's/Device [A-F0-9:]* (.*)/\1/p' | dmenu)
# get macid
macid=$(bt_getmacid "$name")
# use the macid to connect to the bluetooth device
[ -n "$macid" ] && echo "connect $macid" | bluetoothctl

