#!/bin/bash


name=$(cat ~/.bluetooth-devices | cut -d" " -f3- | fzf)
echo "name: $name"

macid=$(cat ~/.bluetooth-devices | grep "$name" | awk '{print $2}')
echo "macid: $macid"

# use the macid to connect to the bluetooth device

echo "connect $macid" | bluetoothctl

