#!/bin/sh
#
# connects a previously paired device

connect() {
	while read -r id; do
		# connect using id
		[ -n "$id" ] && echo "connect $id" | bluetoothctl
	done
}

# list names of paired devices
btls --paired | dmenu | sort -u | btconvert --to-id | connect
