#!/bin/sh

toname () {
	while read -r line
	do
		echo "info $line" | bluetoothctl | awk -F ': ' '/Name/ {print $2}'
	done
}

toid () {
	while read -r line
	do
		echo "devices" | bluetoothctl | awk "/$line\$/ {print \$2}"
	done
}

case "$1" in
	'-n'|'--to-name')
		toname
		;;
	'-i'|'--to-id')
		toid
		;;
esac
