#!/bin/sh

toname () {
	echo "info $1" | bluetoothctl | awk -F ': ' '/Name/ {print $2}'
}

toid () {
	echo "devices" | bluetoothctl | awk "/$1\$/ {print \$2}"
}

case "$1" in
	'-n'|'--to-name')
		toname "$2"
		;;
	'-i'|'--to-id')
		toid "$2"
		;;
esac
