#!/bin/sh

toname() {
	for i in "$@"; do
		bluetoothctl info $i | awk -F': ' '/Name/ {print $2}'
	done
}

toid() {
	for i in "$@"; do
		bluetoothctl paired-devices | awk "/$i\$/ {print \$2}"
	done
}

case "$1" in
	'-n' | '--to-name')
		shift
		toname $@
		;;
	'-i' | '--to-id')
		shift
		toid $@
		;;
esac
