#!/bin/sh
#
# disconnects a currently connected device

disconnect() {
	while read -r id; do
		# disconnect using id
		[ -n "$id" ] && echo "disconnect $id" | bluetoothctl
	done
}

# list names of connected devices
btls --connected | dmenu | sort -u | btconvert --to-id | disconnect
