#!/bin/sh
#
# disconnects a device

# list names of connected devices
btls cn | dmenu | sort -u | while read -r name
do
	# convert name to id
	id=$(btconvert -i "$name")
	# disconnect using id
	[ -n "$id" ] && echo "disconnect $id" | bluetoothctl
done

