#!/bin/sh
#
# disconnects a currently connected device

disconnect() {
	while read -r id; do
		# disconnect using id
		[ -n "$id" ] && echo disconnect $id | bluetoothctl
	done
}

# list names of connected devices
btls --connected | fzfmenu -m | sort -u | xargs btconv -i | disconnect
