#!/bin/sh
#

pairednames() {
	echo devices | bluetoothctl | sed -rn 's/Device [A-F0-9:]* (.*)/\1/p'
}

connectednames() {
	echo devices | bluetoothctl | awk '/Device/ {print $2}' | while read -r i; do
		echo info $i | bluetoothctl | grep 'Connected: yes' && echo $i
	done | xargs btconv -n
}

case "$1" in
	'-p' | '--paired')
		pairednames
		;;
	'-c' | '--connected')
		connectednames
		;;
esac
