#!/bin/dash
#
# increases brightness by 5%
#


# calculate 5% of maximum brightness
diff=$(echo "0.05 * $(bright_getmax)" | bc)
# add 5% to current brightness
bright_new=$(echo "$(bright_get) + $diff" | bc)

# remove decimal places
backlight=${bright_new%.*}

echo "$backlight" > /sys/class/backlight/intel_backlight/brightness

# send notification
dunst_brightness &

