#!/bin/bash
#
# reduces brightness by 2%
#


# calculate 2% of maximum brightness
diff=$(echo "0.02 * $(bright_getmax)" | bc)
# subtract 2% from current brightness
bright_new=$(echo "$(bright_get) - $diff" | bc)

# remove decimal places
backlight=${bright_new%.*}

echo "$backlight" > /sys/class/backlight/intel_backlight/brightness

# send notification
dunst_brightness

