#!/bin/sh

# terminate already running bar instances
pkill -x polybar

# wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do true; done

# display polybar on all monitors
polybar --list-monitors | cut -d: -f1 | while read -r m; do
	echo $m: polybar launched
	MONITOR=$m polybar --reload example &
done

echo polybar launched
