#!/bin/sh

# terminate already running bar instances
killall -q polybar

# wait until the processes have been shut down
while pgrep -x polybar > /dev/null; do sleep 1; done

# display polybar on all monitors
for m in $(polybar --list-monitors | cut -d":" -f1); do
	MONITOR=$m polybar --reload example &
done

echo "Polybar launched..."
