#!/bin/sh

# terminate already running bar instances
killall -q polybar

# wait until the processes have been shut down
while pgrep -x polybar > /dev/null; do sleep 1; done

# for m in $(polybar --list-monitors | cut -d":" -f1); do
# 	MONITOR=$m polybar --reload example &
# done

# in case the above doesn't work, try this
if type "xrandr"; then
	for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
		MONITOR=$m polybar --reload example &
	done
else
	polybar --reload example &
fi

echo "Polybar launched..."
