#!/bin/sh
#
# dpms standby: standby monitor
# dpms suspend: suspend monitor
# dpms off: turn off monitor
# screensaver timeout: call xss-lock notifier
# screensaver cycle: call xss-lock locker

# retrieve config variables
. "$XDG_CONFIG_HOME"/bin/lock_vars

# set dpms timeouts
xset dpms $standby $suspend $off
# set screensaver timeouts
xset s $timeout $cycle

# restart locker
pkill -x xss-lock
xss-lock -n dimscreen -- slock &
