#!/bin/sh

# retrieve config variables
. $XDG_CONFIG_HOME/bin/lock_vars

# set dpms timeouts
xset dpms $s_standby $s_suspend $s_off
# lock on notify timeout
xset s $s_notify 0
pkill xss-lock
xss-lock -n dimscreen -- slock &
