#!/bin/sh

doaction() {
	read -r option

	case "$option" in
		'lock')
			slock
			;;
		'quit')
			bspc quit
			;;
		'refresh')
			bspc wm -r
			;;
		'reboot')
			reboot
			;;
		'shutdown')
			shutdown now
			;;
	esac
}

echo 'lock quit refresh reboot shutdown' | tr ' ' '\n' | dmenu | doaction
