#!/bin/sh

export XDG_RUNTIME_DIR=/run/user/1000
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export DISPLAY=:0

external=HDMI-1
laptop=eDP-1

xrandr | grep "$external connected" >/dev/null &&
	xrandr --output "$external" --auto --right-of "$laptop" ||
	xrandr --output "$external" --auto --off
