#!/bin/sh

output=HDMI-1
current=eDP-1

case "$1" in
	'-e' | '--extend')
		xrandr --output "$output" --auto --left-of "$current"
		;;
	'-d' | '--disconnect')
		xrandr --auto && xrandr --output "$output" --off
		;;
esac
