#!/bin/bash
#
# $1 is file with links
#

links=$(grep -oP '\(\K[^\)]+' $1 | grep 'https://www.youtube.com/watch?v=')

for link in $links
do
	echo "link: $link"
	youtube-dl --extract-audio --audio-format mp3 $link
done

