#!/bin/sh

# set wallpaper
hsetroot -solid "#282828" & # gruvbox

# sets the statusbar
nohup dwm_setstatbar > ~/.scripts/.logs/dwm_setstatbar &

# compositor
# do i need this?
compton &

# battery low/full notifications
nohup batt_notifier > ~/.scripts/.logs/batt_notifier &

# initialize screensaver
nohup screensaver_init > ~/.scripts/.logs/screensaver_init &

# initialize meta scripts
nohup scripts_autocp > ~/.scripts/.logs/scripts_autocp &
nohup scripts_autorm > ~/.scripts/.logs/scripts_autorm &

# notification daemon
dunst &

