#!/bin/dash

options='lock quit refresh restart shutdown'
option=$(echo $options | tr ' ' '\n' | dmenu)

case "$option" in
	"lock")
		echo "lock screen"
		slock
		;;
	"quit")
		echo "quit dwm"
		dwm_quit
		;;
	"refresh")
		echo "refresh dwm"
		killall -q dwm
		;;
	"restart")
		echo "restart"
		reboot
		;;
	"shutdown")
		echo "shutdown"
		shutdown now
		;;
	*)
		echo "choose a valid option"
		;;
esac

