#!/bin/sh

SCRIPTS_DIR=/home/kesav/.local/scripts

# startup script
dwm_init &

# execute dwm
while true
do
	# log stderror to a file
	dwm 2> $SCRIPTS_DIR/.logs/dwm.log

	# no error logging
	# dwm >/dev/null 2>&1
done

