#! /bin/bash

# weather
#
# short format: temperature
# long forrmat: temperature
#
getweather() {
	temp="$(curl -s 'wttr.in/Phoenix?format=%t')"
	error=$(echo $temp | grep '[eE]rror')

	if [ -n "$error" ]
	then
		echo "  (error)"
	else
		echo "  $temp"
	fi
}


# wifi
#
# short format: ssid
# long format: ssid, upspeed, downspeed, signal
getwifi() {
	wifi=$(wifi_getssid)

	if [ -z "$wifi" ]
	then
		echo "睊  (disconnected)"
	else
		echo "  $(wifi_getssid)"
	fi
}

# volume
#
# short format: volume level
# no long format
getvolume() {
	if [ "$(audio_ismuted)" = "yes" ]
	then
		echo "  $(audio_getvolume)%"
	else
		echo "  $(audio_getvolume)%"
	fi
}

# brightness
#
# short format: brightness level
# no long format
getbrightness() {
	echo "  $(bright_getp)%"
}

# battery
#
# short format: battery level, status
# long format: battery level, status, time left
#
# TODO: (long format) display time left until full charge/time until dead
# TODO: if multiple batteries present, only display the first one
getbattery() {
	status=$(batt_getstatus)

	if [ "$status" = "Discharging" ]
	then
		echo "  $(batt_getp)%"
	elif [ "$status" = "Charging" ]
	then
		echo "  $(batt_getp)%"
	elif [ "$status" = "Full" ]
	then
		echo "  $(batt_getp)%"
	else
		echo "be  $(batt_getp)%"
	fi
}

# datetime
#
# short format: day of the week, 12 hour time
# long format: month/day/year, 24 hour time
getdatetime() {
	time="$(date +"%H:%M")"
	date="$(date +"%a %m/%d")"

	echo "  $time $date"
}

# all statuses

getstatus() {
	echo -en "\x02 $(getweather) "
	echo -en "\x03 $(getwifi) "
	echo -en "\x04 $(getvolume) "
	echo -en "\x02 $(getbrightness) "
	echo -en "\x03 $(getbattery) "
	echo -en "\x04 $(getdatetime) "
	echo -en "\x01"
}

while true
do
	xsetroot -name "$(getstatus)"
	sleep .1
done

