#!/bin/sh

getweather() {
	temp="$(curl -s 'wttr.in/Phoenix?format=%t')"
	error=$(echo $temp | grep '[eE]rror')

	if [ -n "$error" ]
	then
		echo "  (e)"
	else
		echo "  $temp"
	fi
}


#
# short format: ssid
# long format: ssid, upspeed, downspeed, signal
#
getwifi () {
	wifi=$(wifi_getssid)

	if [ -z "$wifi" ]
	then
		echo "睊  (disconnected)"
	else
		echo "  $(wifi_getssid)"
	fi
}

getvolume () {
	if [ "$(audio_ismuted)" = "yes" ]
	then
		echo "  $(audio_getvolume)%"
	else
		echo "  $(audio_getvolume)%"
	fi
}

getbrightness () {
	echo "  $(bright_getp)%"
}

#
# short format: battery level, status
# long format: battery level, status, time left
#
# TODO: (long format) display time left until full charge/time until dead
#
getbattery () {
	echo "$(getbatteryicon) $(battinfo -p)%"
}

getbatteryicon () {
	case "$(battinfo -s)" in
		'Discharging')
			echo ' '
			;;
		'Charging')
			echo ''
			;;
		'Full')
			echo ' '
			;;
		*)
			echo 'be'
			;;
	esac
}

gettime () {
	time="$(date +"%I:%M:%S %p")"
	echo "  $time"
}

getdate () {
	date="$(date +"%a, %b %d")"
	echo "  $date"
}

# all statuses

getstatus () {
	echo -n "\02 $(getweather) "
	echo -n "\03 $(getwifi) "
	echo -n "\04 $(getvolume) "
	echo -n "\02 $(getbrightness) "
	echo -n "\03 $(getbattery) "
	echo -n "\04 $(gettime) "
	echo -n "\02 $(getdate) "
	echo -n "\01"
}

while true
do
	xsetroot -name "$(getstatus)"
	# echo "$(getstatus)"
	sleep .1
done

