#! /bin/bash
#
# dwm startup script
#
# powerline symbols
# 
# 
# 
# 
#
# other symbols
#     wifi
#     volume-on
#     volume-muted
#     brightness
#     battery full
#     battery charging
#     battery discharging
#     time
#
# TODO: add colors to signify status
# TODO: implement toggle between short and long format

# weather
#
# short format: temperature
# long forrmat: temperature
#
# getweather() {
# 	temp="$(curl -s wttr.in/Phoenix?format=%t)"
# 	error=$(echo $temp | grep '[eE]rror')

# 	if [ -n "$error" ]
# 	then
# 		echo "  (error)"
# 	else
# 		echo "  $(curl -s wttr.in/Phoenix?format=%t)"
# 	fi

#  }


# wifi
#
# short format: ssid
# long format: ssid, upspeed, downspeed, signal
getwifi() {
	wifi=$(wifi_getssid)

	if [ -z "$wifi" ]
	then
		echo "  (disconnected)"
	else
		echo "  $(wifi_getssid)"
	fi

	# echo "wifi: $(wifi_getssid)"
}

# volume
#
# short format: volume level
# no long format
getvolume() {
	ismuted=$(audio_ismuted)

	if [ "$ismuted" = "muted" ]
	then
		# why is the mute symbol a garbage can?
		# echo "  $(audio_getvolume)%"
		echo "m  $(audio_getvolume)"
	elif [ "$ismuted" = "not muted" ]
	then
		echo "  $(audio_getvolume)%"
	fi
}

# brightness
#
# short format: brightness level
# no long format
getbrightness() {
	echo "  $(bright_getp)%"
}

# battery
#
# short format: battery level, status
# long format: battery level, status, time left
#
# TODO: (long format) display time left until full charge/time until dead
# TODO: if multiple batteries present, only display the first one
getbattery() {
	status=$(batt_getstatus)

	if [ "$status" = "Discharging" ]
	then
		echo "  $(batt_getp)%"
	elif [ "$status" = "Charging" ]
	then
		echo "  $(batt_getp)%"
	elif [ "$status" = "Full" ]
	then
		echo "  $(batt_getp)%"
	else
		echo "e  $(batt_getp)%"
	fi
}

# datetime
#
# short format: day of the week, 12 hour time
# long format: month/day/year, 24 hour time
getdatetime() {
	date="$(date +"%a")"
	time="$(date +"%I:%M %P")"

	echo "  $date $time"

	# date_long="$(date +"%m/%d/%Y")"
	# time_long="$(date +"%H:%M:%S")"

	# echo "date: $date_long $time_long"
}

# all statuses

getstatus() {
	# echo -e "\x02 $(getwifi) \x01 \x02 $(getvolume) \x01 \x02 $(getbrightness) \x01 \x02 $(getbattery) \x01 \x02 $(getdatetime) \x01"
	# echo -e "\x01 $(getwifi) \x01 \x01 $(getvolume) \x01 \x01 $(getbrightness) \x01 \x01 $(getbattery) \x01 \x01 $(getdatetime) \x01"
	# echo -e " $(getweather) | $(getwifi)  |  $(getvolume)  |  $(getbrightness)  |  $(getbattery)  |  $(getdatetime) "
	# echo -e " $(getwifi)  |  $(getvolume)  |  $(getbrightness)  |  $(getbattery)  |  $(getdatetime) "
	echo -e " $(getwifi) "
}

while true
do
	xsetroot -name "$(getstatus)"
	sleep .1
done

