#!/bin/sh

# notification daemon
nohup dunst >$XDG_CACHE_HOME/bin/dunst.log 2>&1 &

# set wallpaper
hsetroot -solid "#282828" & # gruvbox

# sets the statusbar
nohup dwm_setstatbar >$XDG_CACHE_HOME/bin/dwm_setstatbar.log 2>&1 &

# battery low/full notifications
nohup battalarms >$XDG_CACHE_HOME/bin/battalarms.log 2>&1 &

# initialize screensaver
ssaver_init &

