#!/bin/sh

# set wallpaper
hsetroot -solid "#282828"
# sets the statusbar
setstatus &
# initialize screensaver
lockrc &

# battery low/full notifications
battalarms >$XDG_CACHE_HOME/bin/battalarms.log 2>&1 &

