#!/bin/sh

options='lock quit refresh restart shutdown'
option=$(echo $options | tr ' ' '\n' | dmenu)

case "$option" in
	'lock')
		slock
		;;
	'quit')
		killall dwm_setstatbar
		killall xinitrc
		;;
	'refresh')
		killall -q dwm
		;;
	'restart')
		reboot
		;;
	'shutdown')
		shutdown now
		;;
esac

