#!/bin/sh

doaction () {
	read -r option

	case "$option" in
		'lock')
			slock
			;;
		'quit')
			killall dwm_setstatbar
			killall xinitrc
			;;
		'refresh')
			killall -q dwm
			;;
		'restart')
			reboot
			;;
		'shutdown')
			shutdown now
			;;
	esac
}


echo 'lock quit refresh restart shutdown' | tr ' ' '\n' | dmenu | doaction

