#!/bin/sh

# startup script
~/.scripts/dwm/startup &

# sets the statusbar
# ~/.scripts/dwm/set_statusbar &

# execute dwm
while true
do
	# log stderror to a file
	dwm 2> ~/.dwm.log

	# no error logging
	# dwm >/dev/null 2>&1
done

