#!/bin/sh

#
# this makes the script really slow
# find a faster way of reporting weather
#
# getweather() {
# 	temp="$(curl -s 'wttr.in/chandler?format=%t' | grep -Eo '(\+|\-)[0-9]*°F')"
# 	[ -n "$temp"  ] && echo "  $temp"
# }

#
# short format: ssid
# long format: ssid, upspeed, downspeed, signal
#
getwifi () {
	ssid=$(netinfo)

	if [ -z "$ssid" ]
	then
		echo "睊  (disconnected)"
	else
		echo "  $ssid"
	fi
}

volumebar () {
	echo "$(volumeicon) $(volctl --get-volume)%"
}

volumeicon () {
	case "$(volctl --is-muted)" in
		'yes')
			echo " "
			;;
		*)
			echo " "
			;;
	esac
}

getbrightness () {
	echo "  $(getbright --percent)%"
}

#
# short format: battery level, status
# long format: battery level, status, time left
#
# TODO: (long format) display time left until full charge/time until dead
#
batterybar () {
	echo "$(batteryicon) $(battinfo -p)%"
}

batteryicon () {
	case "$(battinfo -s)" in
		'Discharging')
			echo ' '
			;;
		'Charging')
			echo ''
			;;
		'Full')
			echo ' '
			;;
		*)
			echo 'be'
			;;
	esac
}

gettime () {
	time="$(date +"%I:%M %p")"
	echo "  $time"
}

getdate () {
	date="$(date +"%a, %b %d")"
	echo "  $date"
}

# all statuses

getstatus () {
	# echo -n "\02 $(getweather) "
	echo -n "\03 $(getwifi) "
	echo -n "\04 $(volumebar) "
	echo -n "\02 $(getbrightness) "
	echo -n "\03 $(batterybar) "
	echo -n "\04 $(gettime) "
	echo -n "\02 $(getdate) "
	echo -n "\01"
}

while true
do
	xsetroot -name "$(getstatus)"
	# echo "$(getstatus)"
	sleep .1
done

