#!/bin/sh
#
# returns info on battery
# -p or --percent returns battery percentage
# -s or --status returns status (charging/discharging/full)

case "$1" in
	'-p' | '--percent')
		# print battery percentage
		cat /sys/class/power_supply/BAT0/capacity
		;;
	'-s' | '--status')
		# print battery status
		cat /sys/class/power_supply/BAT0/status
		;;
esac
