#!/bin/sh

# critical threshold capacity
critical=9
# low threshold capacity
low=15

# time between notifications (in seconds)
waittime=60

#
# sends a notification when the current battery level is
# - is not charging
# - below the critical threshold
#
# $1 is battery status: charging/discharging/full
# $2 is current battery capacity
# $3 is critical capacity threshold
#
batterycritical () {
	if [ "$1" = "Discharging" ] && [ "$2" -le "$3" ]
	then
		notifybatt 'critical'  &
	fi
}

#
# sends a notification when the current battery level is
# - is not charging
# - above the critical threshold
# - below the low threshold
#
# $1 is battery status: charging/discharging/full
# $2 is current battery capacity
# $3 is critical capacity threshold
# $4 is low capacity threshold
#
batterylow () {
	if [ "$1" = "Discharging" ] && [ "$2" -gt "$3" ] && [ "$2" -le "$4" ]
	then
		notifybatt 'low' &
	fi
}

#
# sends a notification when the battery is full
#
# $1 is battery status: charging/discharging/full
#
batteryfull () {
	[ "$1" = "Full" ] && notifybatt 'full' &
}

#
# $1 is critical capacity threshold
# $2 is low capacity threshold
#
batterycheck () {

	status=$(battinfo -s)
	capacity=$(battinfo -p)

	echo "status:		$status"
	echo "capacity:	$capacity"
	echo "critical:	$critical"
	echo "low:		$low"
	echo ""

	batterycritical $status $capacity $1
	batterylow $status $capacity $1 $2
	batteryfull $status
}


while true
do
	batterycheck $critical $low
	sleep $waittime
done

